[package]
name = "book_store_api"
version = "0.1.0"
edition = "2021"

[profile.release]
opt-level = "z"          # Optimize for size
lto = "thin"             # Use Link Time Optimization
codegen-units = 1        # Single codegen unit for better optimization
debug = true             # Debug symbols in release build
panic = "abort"          # Abort on panic for smaller binary
incremental = false      # Disable incremental compilation

[dependencies]
rocket = {version = "0.5.1", features = ["json"]}
sea-orm-migration = "1.0.1"
sea-orm = { version = "1.0.1", features = [
    "sqlx-mysql",
    "runtime-async-std-native-tls",
    "macros",
    "with-chrono",
    "debug-print"
]}
jsonwebtoken = "9.3.0"
bcrypt = "0.15.1"
dotenvy = "0.15.7"